[2022-11-02T05:34:53.980-0300] {processor.py:154} INFO - Started process (PID=4754) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:34:53.981-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T05:34:53.982-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:34:53.982-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:34:53.994-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:34:53.993-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T05:34:53.994-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:34:53.994-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T05:34:53.994-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:34:54.011-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2022-11-02T05:41:23.141-0300] {processor.py:154} INFO - Started process (PID=6710) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:41:23.150-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T05:41:23.151-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:41:23.151-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:41:23.186-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:41:23.185-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T05:41:23.186-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:41:23.186-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T05:41:23.186-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:41:23.211-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.073 seconds
[2022-11-02T05:41:53.763-0300] {processor.py:154} INFO - Started process (PID=7064) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:41:53.764-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T05:41:53.765-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:41:53.765-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:41:53.790-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:41:53.789-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T05:41:53.790-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:41:53.790-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T05:41:53.791-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:41:53.828-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.069 seconds
[2022-11-02T05:42:24.520-0300] {processor.py:154} INFO - Started process (PID=7301) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:42:24.522-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T05:42:24.522-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:42:24.522-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:42:24.539-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:42:24.538-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T05:42:24.539-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:42:24.539-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T05:42:24.539-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:42:24.566-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2022-11-02T05:42:54.669-0300] {processor.py:154} INFO - Started process (PID=7540) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:42:54.670-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T05:42:54.670-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:42:54.670-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:42:54.683-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:42:54.683-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T05:42:54.684-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:42:54.683-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T05:42:54.684-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:42:54.708-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2022-11-02T05:43:25.394-0300] {processor.py:154} INFO - Started process (PID=7770) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:43:25.395-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T05:43:25.396-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:43:25.396-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:43:25.409-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:43:25.408-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T05:43:25.409-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:43:25.409-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T05:43:25.409-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:43:25.434-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2022-11-02T05:43:56.386-0300] {processor.py:154} INFO - Started process (PID=8007) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:43:56.387-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T05:43:56.388-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:43:56.388-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:43:56.455-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:43:56.454-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T05:43:56.455-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:43:56.455-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T05:43:56.455-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:43:56.643-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.263 seconds
[2022-11-02T05:44:27.764-0300] {processor.py:154} INFO - Started process (PID=8386) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:44:27.775-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T05:44:27.776-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:44:27.776-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:44:27.906-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:44:27.906-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T05:44:27.906-0300] {logging_mixin.py:120} INFO - [2022-11-02T05:44:27.906-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T05:44:27.907-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T05:44:27.963-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.208 seconds
[2022-11-02T15:55:18.956-0300] {processor.py:154} INFO - Started process (PID=11810) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:55:18.958-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T15:55:18.958-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:55:18.958-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:55:18.970-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:55:18.969-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T15:55:18.970-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:55:18.970-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T15:55:18.970-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:55:19.033-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2022-11-02T15:55:49.261-0300] {processor.py:154} INFO - Started process (PID=12124) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:55:49.261-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T15:55:49.263-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:55:49.263-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:55:49.301-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:55:49.297-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T15:55:49.301-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:55:49.301-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T15:55:49.306-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:55:49.369-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.111 seconds
[2022-11-02T15:56:20.522-0300] {processor.py:154} INFO - Started process (PID=12454) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:56:20.526-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T15:56:20.529-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:56:20.526-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:56:20.563-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:56:20.563-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T15:56:20.563-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:56:20.563-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T15:56:20.563-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:56:20.589-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2022-11-02T15:56:51.373-0300] {processor.py:154} INFO - Started process (PID=12699) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:56:51.378-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T15:56:51.381-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:56:51.381-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:56:51.403-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:56:51.402-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T15:56:51.403-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:56:51.403-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T15:56:51.403-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:56:51.454-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2022-11-02T15:57:22.350-0300] {processor.py:154} INFO - Started process (PID=12939) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:57:22.352-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T15:57:22.352-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:57:22.352-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:57:22.363-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:57:22.362-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T15:57:22.363-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:57:22.363-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T15:57:22.363-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:57:22.385-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2022-11-02T15:57:52.654-0300] {processor.py:154} INFO - Started process (PID=13172) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:57:52.655-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T15:57:52.656-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:57:52.656-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:57:52.671-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:57:52.671-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T15:57:52.672-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:57:52.671-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T15:57:52.672-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:57:52.696-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2022-11-02T15:58:23.581-0300] {processor.py:154} INFO - Started process (PID=13404) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:58:23.584-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T15:58:23.585-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:58:23.585-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:58:23.598-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:58:23.597-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T15:58:23.598-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:58:23.598-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T15:58:23.598-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:58:23.625-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-11-02T15:58:53.849-0300] {processor.py:154} INFO - Started process (PID=13631) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:58:53.850-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T15:58:53.850-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:58:53.850-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:58:53.862-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:58:53.862-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T15:58:53.863-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:58:53.863-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T15:58:53.863-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:58:53.890-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-11-02T15:59:24.278-0300] {processor.py:154} INFO - Started process (PID=13858) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:59:24.279-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T15:59:24.280-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:59:24.280-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:59:24.292-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:59:24.291-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T15:59:24.292-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:59:24.292-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T15:59:24.292-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:59:24.316-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2022-11-02T15:59:55.045-0300] {processor.py:154} INFO - Started process (PID=14085) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:59:55.046-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T15:59:55.046-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:59:55.046-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:59:55.063-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:59:55.062-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T15:59:55.063-0300] {logging_mixin.py:120} INFO - [2022-11-02T15:59:55.063-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T15:59:55.063-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T15:59:55.091-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-11-02T16:00:26.137-0300] {processor.py:154} INFO - Started process (PID=14334) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:00:26.138-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:00:26.139-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:00:26.139-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:00:26.151-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:00:26.150-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:00:26.151-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:00:26.151-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:00:26.151-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:00:26.176-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2022-11-02T16:00:56.763-0300] {processor.py:154} INFO - Started process (PID=14578) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:00:56.764-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:00:56.765-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:00:56.765-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:00:56.778-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:00:56.777-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:00:56.778-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:00:56.778-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:00:56.779-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:00:56.802-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2022-11-02T16:01:27.068-0300] {processor.py:154} INFO - Started process (PID=14819) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:01:27.072-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:01:27.073-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:01:27.073-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:01:27.084-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:01:27.083-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:01:27.084-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:01:27.084-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:01:27.084-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:01:27.109-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2022-11-02T16:01:57.610-0300] {processor.py:154} INFO - Started process (PID=15064) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:01:57.611-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:01:57.612-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:01:57.612-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:01:57.622-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:01:57.622-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:01:57.622-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:01:57.622-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:01:57.622-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:01:57.647-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2022-11-02T16:02:27.906-0300] {processor.py:154} INFO - Started process (PID=15318) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:02:27.907-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:02:27.908-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:02:27.908-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:02:27.921-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:02:27.920-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:02:27.921-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:02:27.921-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:02:27.921-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:02:27.946-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2022-11-02T16:02:59.781-0300] {processor.py:154} INFO - Started process (PID=15586) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:02:59.781-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:02:59.782-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:02:59.782-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:02:59.793-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:02:59.793-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:02:59.794-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:02:59.793-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:02:59.794-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:02:59.937-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.159 seconds
[2022-11-02T16:03:30.559-0300] {processor.py:154} INFO - Started process (PID=15901) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:03:30.561-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:03:30.562-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:03:30.562-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:03:30.576-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:03:30.576-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:03:30.576-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:03:30.576-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:03:30.577-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:03:30.596-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2022-11-02T16:04:01.063-0300] {processor.py:154} INFO - Started process (PID=16147) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:04:01.064-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:04:01.064-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:04:01.064-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:04:01.080-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:04:01.079-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:04:01.080-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:04:01.080-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:04:01.080-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:04:01.109-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.049 seconds
[2022-11-02T16:04:31.203-0300] {processor.py:154} INFO - Started process (PID=16389) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:04:31.205-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:04:31.205-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:04:31.205-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:04:31.216-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:04:31.215-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:04:31.216-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:04:31.216-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:04:31.216-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:04:31.242-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2022-11-02T16:05:01.989-0300] {processor.py:154} INFO - Started process (PID=16629) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:05:01.990-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:05:01.990-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:05:01.990-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:05:02.002-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:05:02.001-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:05:02.002-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:05:02.002-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:05:02.002-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:05:02.029-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2022-11-02T16:05:32.518-0300] {processor.py:154} INFO - Started process (PID=16883) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:05:32.520-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:05:32.526-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:05:32.521-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:05:32.629-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:05:32.629-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:05:32.629-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:05:32.629-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:05:32.629-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:05:32.731-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.232 seconds
[2022-11-02T16:06:03.040-0300] {processor.py:154} INFO - Started process (PID=17134) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:06:03.041-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:06:03.041-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:06:03.041-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:06:03.073-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:06:03.071-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:06:03.073-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:06:03.073-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:06:03.073-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:06:03.116-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2022-11-02T16:06:33.593-0300] {processor.py:154} INFO - Started process (PID=17394) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:06:33.595-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:06:33.596-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:06:33.596-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:06:33.633-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:06:33.629-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:06:33.633-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:06:33.633-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:06:33.634-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:06:33.680-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2022-11-02T16:07:04.086-0300] {processor.py:154} INFO - Started process (PID=17633) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:07:04.086-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:07:04.087-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:07:04.087-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:07:04.134-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:07:04.134-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:07:04.134-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:07:04.134-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:07:04.135-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:07:04.178-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2022-11-02T16:07:35.137-0300] {processor.py:154} INFO - Started process (PID=17878) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:07:35.139-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:07:35.139-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:07:35.139-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:07:35.149-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:07:35.149-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:07:35.149-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:07:35.149-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:07:35.150-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:07:35.172-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2022-11-02T16:08:05.822-0300] {processor.py:154} INFO - Started process (PID=18117) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:08:05.895-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:08:05.905-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:08:05.905-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:08:05.964-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:08:05.955-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:08:05.964-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:08:05.964-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:08:05.965-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:08:06.037-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.223 seconds
[2022-11-02T16:08:36.379-0300] {processor.py:154} INFO - Started process (PID=18362) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:08:36.381-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:08:36.382-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:08:36.382-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:08:36.407-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:08:36.406-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:08:36.407-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:08:36.407-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:08:36.407-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:08:36.442-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2022-11-02T16:09:06.986-0300] {processor.py:154} INFO - Started process (PID=18599) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:09:06.992-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:09:06.993-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:09:06.993-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:09:07.006-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:09:07.005-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:09:07.006-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:09:07.006-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:09:07.006-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:09:07.046-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2022-11-02T16:09:37.744-0300] {processor.py:154} INFO - Started process (PID=18855) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:09:37.756-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:09:37.756-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:09:37.756-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:09:37.790-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:09:37.789-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:09:37.791-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:09:37.791-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:09:37.791-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:09:37.841-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.120 seconds
[2022-11-02T16:10:08.259-0300] {processor.py:154} INFO - Started process (PID=19104) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:10:08.274-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:10:08.274-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:10:08.274-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:10:08.318-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:10:08.317-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:10:08.318-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:10:08.318-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:10:08.318-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:10:08.355-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2022-11-02T16:10:38.540-0300] {processor.py:154} INFO - Started process (PID=19356) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:10:38.542-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:10:38.544-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:10:38.542-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:10:38.562-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:10:38.561-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:10:38.562-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:10:38.562-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:10:38.562-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:10:38.584-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-11-02T16:11:01.853-0300] {processor.py:154} INFO - Started process (PID=19791) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:11:01.855-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:11:01.856-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:11:01.855-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:11:01.923-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:11:01.923-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:11:01.923-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:11:01.923-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:11:01.925-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:11:02.015-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.166 seconds
[2022-11-02T16:11:32.623-0300] {processor.py:154} INFO - Started process (PID=20051) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:11:32.624-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:11:32.625-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:11:32.625-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:11:32.643-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:11:32.641-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:11:32.643-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:11:32.643-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:11:32.644-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:11:32.676-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2022-11-02T16:12:03.291-0300] {processor.py:154} INFO - Started process (PID=20300) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:12:03.292-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:12:03.293-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:12:03.292-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:12:03.310-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:12:03.309-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:12:03.310-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:12:03.310-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:12:03.310-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:12:03.341-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2022-11-02T16:12:33.431-0300] {processor.py:154} INFO - Started process (PID=20554) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:12:33.433-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:12:33.433-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:12:33.433-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:12:33.444-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:12:33.444-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:12:33.444-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:12:33.444-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:12:33.444-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:12:33.476-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2022-11-02T16:13:13.612-0300] {processor.py:154} INFO - Started process (PID=21071) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:13:13.614-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:13:13.614-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:13:13.614-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:13:13.656-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:13:13.655-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:13:13.656-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:13:13.656-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:13:13.656-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:13:13.735-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.135 seconds
[2022-11-02T16:13:44.129-0300] {processor.py:154} INFO - Started process (PID=21339) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:13:44.131-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:13:44.131-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:13:44.131-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:13:44.142-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:13:44.142-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:13:44.142-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:13:44.142-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:13:44.142-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:13:44.167-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2022-11-02T16:14:14.623-0300] {processor.py:154} INFO - Started process (PID=21604) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:14:14.625-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:14:14.625-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:14:14.625-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:14:14.651-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:14:14.651-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:14:14.651-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:14:14.651-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:14:14.652-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:14:14.687-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2022-11-02T16:14:45.394-0300] {processor.py:154} INFO - Started process (PID=21859) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:14:45.396-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:14:45.397-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:14:45.397-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:14:45.413-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:14:45.413-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:14:45.414-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:14:45.414-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:14:45.414-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:14:45.437-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-11-02T16:15:15.965-0300] {processor.py:154} INFO - Started process (PID=22150) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:15:15.966-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:15:15.966-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:15:15.966-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:15:15.980-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:15:15.980-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:15:15.980-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:15:15.980-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:15:15.980-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:15:16.004-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2022-11-02T16:15:46.529-0300] {processor.py:154} INFO - Started process (PID=22396) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:15:46.533-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:15:46.535-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:15:46.535-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:15:46.546-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:15:46.545-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:15:46.546-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:15:46.546-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:15:46.546-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:15:46.564-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2022-11-02T16:16:17.321-0300] {processor.py:154} INFO - Started process (PID=22647) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:16:17.322-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:16:17.323-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:16:17.322-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:16:17.336-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:16:17.335-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:16:17.336-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:16:17.336-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:16:17.336-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:16:17.359-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2022-11-02T16:16:48.012-0300] {processor.py:154} INFO - Started process (PID=22902) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:16:48.013-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:16:48.014-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:16:48.014-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:16:48.025-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:16:48.024-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:16:48.025-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:16:48.025-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:16:48.025-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:16:48.051-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2022-11-02T16:17:18.777-0300] {processor.py:154} INFO - Started process (PID=23151) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:17:18.780-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:17:18.781-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:17:18.781-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:17:18.796-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:17:18.796-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:17:18.796-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:17:18.796-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:17:18.797-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:17:18.829-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.054 seconds
[2022-11-02T16:17:49.058-0300] {processor.py:154} INFO - Started process (PID=23390) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:17:49.060-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:17:49.060-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:17:49.060-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:17:49.072-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:17:49.072-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:17:49.073-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:17:49.073-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:17:49.073-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:17:49.100-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-11-02T16:18:19.348-0300] {processor.py:154} INFO - Started process (PID=23636) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:18:19.349-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:18:19.350-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:18:19.350-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:18:19.364-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:18:19.364-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:18:19.364-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:18:19.364-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:18:19.364-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:18:19.395-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.050 seconds
[2022-11-02T16:18:50.119-0300] {processor.py:154} INFO - Started process (PID=23898) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:18:50.121-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:18:50.121-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:18:50.121-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:18:50.143-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:18:50.142-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:18:50.144-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:18:50.144-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:18:50.144-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:18:50.168-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.057 seconds
[2022-11-02T16:19:21.347-0300] {processor.py:154} INFO - Started process (PID=24171) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:19:21.350-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:19:21.355-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:19:21.354-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:19:21.425-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:19:21.420-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:19:21.425-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:19:21.425-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:19:21.425-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:19:21.487-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.151 seconds
[2022-11-02T16:19:52.466-0300] {processor.py:154} INFO - Started process (PID=24432) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:19:52.468-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:19:52.469-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:19:52.469-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:19:52.481-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:19:52.480-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:19:52.481-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:19:52.481-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:19:52.481-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:19:52.508-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2022-11-02T16:20:23.896-0300] {processor.py:154} INFO - Started process (PID=24691) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:20:23.896-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:20:23.897-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:20:23.897-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:20:23.908-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:20:23.908-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:20:23.909-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:20:23.908-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:20:23.909-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:20:23.932-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-11-02T16:20:54.512-0300] {processor.py:154} INFO - Started process (PID=25113) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:20:54.514-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:20:54.514-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:20:54.514-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:20:54.526-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:20:54.525-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:20:54.526-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:20:54.526-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:20:54.526-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:20:54.551-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.042 seconds
[2022-11-02T16:21:24.894-0300] {processor.py:154} INFO - Started process (PID=25511) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:21:24.896-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:21:24.899-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:21:24.899-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:21:24.922-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:21:24.922-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:21:24.923-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:21:24.923-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:21:24.923-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:21:24.967-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2022-11-02T16:21:55.936-0300] {processor.py:154} INFO - Started process (PID=25813) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:21:55.937-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:21:55.938-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:21:55.938-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:21:55.961-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:21:55.953-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:21:55.961-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:21:55.961-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:21:55.961-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:21:56.008-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2022-11-02T16:22:26.544-0300] {processor.py:154} INFO - Started process (PID=26074) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:22:26.546-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:22:26.546-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:22:26.546-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:22:26.570-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:22:26.567-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:22:26.570-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:22:26.570-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:22:26.571-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:22:26.599-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.058 seconds
[2022-11-02T16:22:56.876-0300] {processor.py:154} INFO - Started process (PID=26321) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:22:56.877-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:22:56.878-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:22:56.878-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:22:56.905-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:22:56.903-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:22:56.905-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:22:56.905-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:22:56.905-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:22:56.938-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2022-11-02T16:23:27.351-0300] {processor.py:154} INFO - Started process (PID=26583) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:23:27.356-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:23:27.357-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:23:27.356-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:23:27.381-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:23:27.380-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:23:27.381-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:23:27.381-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:23:27.381-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:23:27.418-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2022-11-02T16:23:58.575-0300] {processor.py:154} INFO - Started process (PID=26928) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:23:58.577-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:23:58.577-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:23:58.577-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:23:58.588-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:23:58.587-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:23:58.588-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:23:58.588-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:23:58.588-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:23:58.612-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2022-11-02T16:24:29.278-0300] {processor.py:154} INFO - Started process (PID=27230) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:24:29.279-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:24:29.279-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:24:29.279-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:24:29.291-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:24:29.291-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:24:29.292-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:24:29.292-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:24:29.292-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:24:29.323-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-11-02T16:24:59.730-0300] {processor.py:154} INFO - Started process (PID=27474) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:24:59.732-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:24:59.732-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:24:59.732-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:24:59.745-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:24:59.745-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:24:59.746-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:24:59.746-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:24:59.746-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:24:59.770-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-11-02T16:25:30.550-0300] {processor.py:154} INFO - Started process (PID=27745) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:25:30.551-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:25:30.551-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:25:30.551-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:25:30.564-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:25:30.563-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:25:30.564-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:25:30.564-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:25:30.564-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:25:30.608-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.061 seconds
[2022-11-02T16:26:01.069-0300] {processor.py:154} INFO - Started process (PID=28004) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:26:01.070-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:26:01.075-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:26:01.072-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:26:01.089-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:26:01.089-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:26:01.090-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:26:01.089-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:26:01.090-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:26:01.147-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2022-11-02T16:26:31.944-0300] {processor.py:154} INFO - Started process (PID=28262) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:26:31.946-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:26:31.946-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:26:31.946-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:26:31.957-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:26:31.956-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:26:31.957-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:26:31.957-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:26:31.957-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:26:31.979-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.037 seconds
[2022-11-02T16:27:03.047-0300] {processor.py:154} INFO - Started process (PID=28634) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:27:03.049-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:27:03.050-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:27:03.049-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:27:03.063-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:27:03.063-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:27:03.063-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:27:03.063-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:27:03.063-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:27:03.087-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2022-11-02T16:27:34.229-0300] {processor.py:154} INFO - Started process (PID=29015) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:27:34.230-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:27:34.231-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:27:34.231-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:27:34.247-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:27:34.245-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:27:34.247-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:27:34.247-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:27:34.247-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:27:34.276-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.052 seconds
[2022-11-02T16:28:05.054-0300] {processor.py:154} INFO - Started process (PID=29372) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:28:05.056-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:28:05.057-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:28:05.056-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:28:05.073-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:28:05.073-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:28:05.073-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:28:05.073-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:28:05.074-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:28:05.106-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.055 seconds
[2022-11-02T16:28:35.994-0300] {processor.py:154} INFO - Started process (PID=29812) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:28:35.997-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:28:35.997-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:28:35.997-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:28:36.055-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:28:36.054-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:28:36.055-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:28:36.055-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:28:36.055-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:28:36.111-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.128 seconds
[2022-11-02T16:29:06.487-0300] {processor.py:154} INFO - Started process (PID=30133) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:29:06.489-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:29:06.489-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:29:06.489-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:29:06.509-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:29:06.508-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:29:06.509-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:29:06.509-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:29:06.509-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:29:06.530-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-11-02T16:29:36.986-0300] {processor.py:154} INFO - Started process (PID=30522) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:29:36.989-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:29:36.990-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:29:36.989-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:29:37.002-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:29:37.002-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:29:37.003-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:29:37.003-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:29:37.003-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:29:37.029-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-11-02T16:30:07.933-0300] {processor.py:154} INFO - Started process (PID=30853) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:30:07.935-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:30:07.935-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:30:07.935-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:30:07.955-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:30:07.951-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:30:07.956-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:30:07.956-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:30:07.956-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:30:07.978-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-11-02T16:30:39.114-0300] {processor.py:154} INFO - Started process (PID=31192) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:30:39.116-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:30:39.117-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:30:39.117-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:30:39.143-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:30:39.142-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:30:39.143-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:30:39.143-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:30:39.143-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:30:39.186-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.074 seconds
[2022-11-02T16:31:10.104-0300] {processor.py:154} INFO - Started process (PID=31532) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:31:10.106-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:31:10.106-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:31:10.106-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:31:10.118-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:31:10.117-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:31:10.119-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:31:10.119-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:31:10.119-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:31:10.144-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2022-11-02T16:31:41.297-0300] {processor.py:154} INFO - Started process (PID=31862) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:31:41.299-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:31:41.300-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:31:41.300-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:31:41.315-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:31:41.315-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:31:41.315-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:31:41.315-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:31:41.316-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:31:41.340-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.046 seconds
[2022-11-02T16:32:12.488-0300] {processor.py:154} INFO - Started process (PID=32201) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:32:12.490-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:32:12.490-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:32:12.490-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:32:12.714-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:32:12.713-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:32:12.714-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:32:12.714-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:32:12.715-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:32:12.751-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.266 seconds
[2022-11-02T16:32:43.384-0300] {processor.py:154} INFO - Started process (PID=32527) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:32:43.386-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:32:43.387-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:32:43.386-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:32:43.399-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:32:43.399-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:32:43.399-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:32:43.399-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:32:43.400-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:32:43.429-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.048 seconds
[2022-11-02T16:33:14.043-0300] {processor.py:154} INFO - Started process (PID=32883) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:33:14.044-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:33:14.045-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:33:14.044-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:33:14.063-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:33:14.062-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:33:14.064-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:33:14.064-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:33:14.064-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:33:14.123-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2022-11-02T16:33:44.608-0300] {processor.py:154} INFO - Started process (PID=33224) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:33:44.618-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:33:44.619-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:33:44.619-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:33:44.656-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:33:44.655-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:33:44.656-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:33:44.656-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:33:44.656-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:33:44.690-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2022-11-02T16:34:15.481-0300] {processor.py:154} INFO - Started process (PID=33573) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:34:15.483-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:34:15.483-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:34:15.483-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:34:15.647-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:34:15.646-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:34:15.647-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:34:15.647-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:34:15.647-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:34:15.690-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.215 seconds
[2022-11-02T16:34:55.423-0300] {processor.py:154} INFO - Started process (PID=34171) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:34:55.425-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:34:55.434-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:34:55.434-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:34:55.447-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:34:55.446-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:34:55.447-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:34:55.447-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:34:55.447-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:34:55.473-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2022-11-02T16:35:25.763-0300] {processor.py:154} INFO - Started process (PID=34516) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:35:25.764-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:35:25.764-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:35:25.764-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:35:25.777-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:35:25.777-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:35:25.778-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:35:25.778-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:35:25.778-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:35:25.808-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.047 seconds
[2022-11-02T16:35:56.080-0300] {processor.py:154} INFO - Started process (PID=34931) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:35:56.082-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:35:56.083-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:35:56.083-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:35:56.097-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:35:56.096-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:35:56.097-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:35:56.097-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:35:56.102-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:35:56.216-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.143 seconds
[2022-11-02T16:36:26.268-0300] {processor.py:154} INFO - Started process (PID=35260) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:36:26.269-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:36:26.269-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:36:26.269-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:36:26.282-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:36:26.282-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:36:26.283-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:36:26.283-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:36:26.283-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:36:26.308-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2022-11-02T16:36:56.904-0300] {processor.py:154} INFO - Started process (PID=35579) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:36:56.906-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:36:56.906-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:36:56.906-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:36:56.919-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:36:56.919-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:36:56.920-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:36:56.920-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:36:56.920-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:36:56.945-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2022-11-02T16:37:27.065-0300] {processor.py:154} INFO - Started process (PID=35981) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:37:27.067-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:37:27.068-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:37:27.068-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:37:27.082-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:37:27.081-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:37:27.082-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:37:27.082-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:37:27.082-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:37:27.115-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.053 seconds
[2022-11-02T16:37:57.894-0300] {processor.py:154} INFO - Started process (PID=36341) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:37:57.897-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:37:57.897-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:37:57.897-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:37:57.948-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:37:57.948-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:37:57.948-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:37:57.948-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:37:57.949-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:37:58.017-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.145 seconds
[2022-11-02T16:38:28.358-0300] {processor.py:154} INFO - Started process (PID=36791) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:38:28.360-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:38:28.361-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:38:28.360-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:38:28.372-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:38:28.372-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:38:28.372-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:38:28.372-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:38:28.373-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:38:28.412-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.059 seconds
[2022-11-02T16:38:59.543-0300] {processor.py:154} INFO - Started process (PID=37223) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:38:59.544-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:38:59.545-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:38:59.545-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:38:59.577-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:38:59.576-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:38:59.578-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:38:59.577-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:38:59.578-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:38:59.605-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2022-11-02T16:39:30.071-0300] {processor.py:154} INFO - Started process (PID=37646) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:39:30.073-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:39:30.073-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:39:30.073-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:39:30.084-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:39:30.083-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:39:30.084-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:39:30.084-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:39:30.085-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:39:30.111-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2022-11-02T16:40:02.066-0300] {processor.py:154} INFO - Started process (PID=37989) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:40:02.093-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:40:02.098-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:40:02.097-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:40:02.125-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:40:02.124-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:40:02.126-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:40:02.126-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:40:02.126-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:40:02.270-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.207 seconds
[2022-11-02T16:40:32.445-0300] {processor.py:154} INFO - Started process (PID=38317) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:40:32.449-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:40:32.454-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:40:32.453-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:40:32.483-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:40:32.482-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:40:32.483-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:40:32.483-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:40:32.483-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:40:32.524-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.083 seconds
[2022-11-02T16:41:02.977-0300] {processor.py:154} INFO - Started process (PID=38755) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:41:02.983-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:41:02.983-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:41:02.983-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:41:03.025-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:41:03.024-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:41:03.025-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:41:03.025-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:41:03.025-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:41:03.052-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2022-11-02T16:41:33.255-0300] {processor.py:154} INFO - Started process (PID=39099) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:41:33.256-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:41:33.256-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:41:33.256-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:41:33.280-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:41:33.279-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:41:33.280-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:41:33.280-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:41:33.281-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:41:33.316-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.064 seconds
[2022-11-02T16:42:03.886-0300] {processor.py:154} INFO - Started process (PID=39471) to work on /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:42:03.887-0300] {processor.py:756} INFO - Processing file /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-02T16:42:03.888-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:42:03.887-0300] {dagbag.py:537} INFO - Filling up the DagBag from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:42:03.904-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:42:03.904-0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-02T16:42:03.904-0300] {logging_mixin.py:120} INFO - [2022-11-02T16:42:03.904-0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-02T16:42:03.904-0300] {processor.py:768} WARNING - No viable dags retrieved from /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-02T16:42:03.933-0300] {processor.py:176} INFO - Processing /home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.063 seconds
