[2022-11-02T17:21:18.359-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: get_produtos_leroy.produtos_leroy manual__2022-11-02T20:21:15.704068+00:00 [queued]>
[2022-11-02T17:21:18.382-0300] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: get_produtos_leroy.produtos_leroy manual__2022-11-02T20:21:15.704068+00:00 [queued]>
[2022-11-02T17:21:18.382-0300] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-02T17:21:18.382-0300] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-02T17:21:18.382-0300] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-02T17:21:18.454-0300] {taskinstance.py:1383} INFO - Executing <Task(_PythonDecoratedOperator): produtos_leroy> on 2022-11-02 20:21:15.704068+00:00
[2022-11-02T17:21:18.464-0300] {standard_task_runner.py:55} INFO - Started process 69127 to run task
[2022-11-02T17:21:18.477-0300] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'get_produtos_leroy', 'produtos_leroy', 'manual__2022-11-02T20:21:15.704068+00:00', '--job-id', '383', '--raw', '--subdir', 'DAGS_FOLDER/ETL_leroy.py', '--cfg-path', '/tmp/tmp1atx729e']
[2022-11-02T17:21:18.478-0300] {standard_task_runner.py:83} INFO - Job 383: Subtask produtos_leroy
[2022-11-02T17:21:18.841-0300] {task_command.py:376} INFO - Running <TaskInstance: get_produtos_leroy.produtos_leroy manual__2022-11-02T20:21:15.704068+00:00 [running]> on host debian
[2022-11-02T17:21:19.187-0300] {taskinstance.py:1590} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=get_produtos_leroy
AIRFLOW_CTX_TASK_ID=produtos_leroy
AIRFLOW_CTX_EXECUTION_DATE=2022-11-02T20:21:15.704068+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-02T20:21:15.704068+00:00
[2022-11-02T17:21:19.192-0300] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/decorators/base.py", line 188, in execute
    return_value = super().execute(context)
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/debian/etlhausz/airflow/dags/ETL_leroy.py", line 84, in produtos_leroy
    for listas in lista_urls:
  File "/home/debian/etlhausz/venv/lib/python3.9/site-packages/airflow/models/xcom_arg.py", line 250, in __iter__
    raise TypeError("'XComArg' object is not iterable")
TypeError: 'XComArg' object is not iterable
[2022-11-02T17:21:19.276-0300] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=get_produtos_leroy, task_id=produtos_leroy, execution_date=20221102T202115, start_date=20221102T202118, end_date=20221102T202119
[2022-11-02T17:21:19.306-0300] {standard_task_runner.py:100} ERROR - Failed to execute job 383 for task produtos_leroy ('XComArg' object is not iterable; 69127)
[2022-11-02T17:21:19.360-0300] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-11-02T17:21:19.517-0300] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
